service: node-serverless-express-dynamodb

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-east-1

useDotenv: true
plugins:
  - serverless-offline
  - serverless-dotenv-plugin

functions:
  api:
    handler: app.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY